export const cv = {
  fullName: "Hajar Rashidi",
  phone: "+46 72 448 76 18",
  email: "hajarrashidi@gmail.com",
  dob: "1996-05-24",
  website: "www.veycloud.com",
  github: "github.com/hajarrashidi",
  workExperience: [
    {
      position: "Software Engineer",
      role: "Fullstack",
      title: "Fullstack Software Engineer at Sogeti",
      description:
        "Hajar har arbetat med flera webbutvecklingsprojekt på Sogeti. Han har ansvarat för SSAB WearIQ:s hemsida som är skriven i React, underhållit Oskarshamns kärnkraftverk, integrerat BankID för Mittuniversitetet, vidareutvecklat Studentbostader.se i React & PHP, och nu hjälper Luftfartsverket att migrera och refaktorisera kod till .NET 8",
      company: "Sogeti",
      location: "Linköping",
      startDate: "Mar 2022",
      endDate: "Nuvarande",
      new_startDate: "2022-03-01",
      new_endDate: "Nuvarande",
      logotype: "/images/sogeti.png",
      skills: [
        // Frontend
        {title: "HTML"},
        {title: "CSS"},
        {title: "JavaScript"},
        {title: "TypeScript"},
        {title: "React.js"},
        {title: "Vue.js"},
        {title: "Tailwind CSS"},
        // Backend
        {title: "Node.js"},
        {title: "PHP"},
        {title: "Laravel"},
        {title: "C#"},
        // Mobile
        {title: "Android Studio"},
        {title: "Flutter"},
        {title: "Dart"},
        // Database
        {title: "SQL Server"},
        {title: "MySQL"},
        // Version Control
        {title: "Git"},
        {title: "Bitbucket"},
        // Cloud & DevOps
        {title: "Azure"},
        {title: "Azure DevOps"},
        // CMS
        {title: "WordPress"},
        // API
        {title: "REST API"},
        // Package Management
        {title: "Composer"},
        // Project Management
        {title: "Jira"},
        // Design
        {title: "Figma"},
      ],
      assignments: [
        {
          title: "LFV",
          period: "Nov 2023 – Nuvarande",
          role: "Fullstack-utvecklare",
          description:
            "Utvecklar och förvaltar LFV.se samt migrerar gammal kod till .NET 8.",
          skills: [
            {title: "React.js"},
            {title: "Node.js"},
            {title: "TypeScript"},
            {title: "Azure DevOps"},
            {title: "C#"},
          ],
        },
        {
          title: "SSAB",
          period: "Oct 2023",
          role: "Systemutvecklare",
          description:
            "Förvaltade SSAB WearIQ:s mobilapp (Flutter), hemsida och API (Node.js, Vue.js).",
          skills: [
            {title: "HTML"},
            {title: "CSS"},
            {title: "JavaScript"},
            {title: "TypeScript"},
            {title: "React.js"},
            {title: "Vue.js"},
            {title: "Node.js"},
            {title: "Android Studio"},
            {title: "Flutter"},
            {title: "Dart"},
            {title: "Git"},
            {title: "Microsoft Azure"},
            {title: "Microsoft Azure DevOps"},
            {title: "Figma"},
          ],
        },
        {
          title: "Oskarshamns kärnkraftverk",
          period: "Oct 2023",
          role: "Systemutvecklare",
          description:
            "Förvaltade OKG:s mobilapp (Flutter) och webbapp (WordPress) med fokus på säkerhet och prestanda.",
          skills: [
            {title: "HTML"},
            {title: "CSS"},
            {title: "JavaScript"},
            {title: "PHP"},
            {title: "Flutter"},
            {title: "Dart"},
            {title: "Git"},
            {title: "Microsoft Azure DevOps"},
            {title: "WordPress"},
            {title: "REST API"},
            {title: "Figma"},
          ],
        },
        {
          title: "Mittuniversitetet",
          period: "Jan 2023 – Sep 2023",
          role: "Fullstack-utvecklare",
          description:
            "Ledde BankID-integration i befintligt system och utvecklade ett open source-bibliotek för BankID version 6.",
          skills: [
            {title: "HTML"},
            {title: "CSS"},
            {title: "JavaScript"},
            {title: "PHP"},
            {title: "Laravel"},
            {title: "Microsoft SQL Server"},
            {title: "Composer"},
            {title: "Atlassian Jira"},
            {title: "Figma"},
          ],
        },
        {
          title: "Stångåstaden AB",
          period: "Aug 2022 – Jan 2023",
          role: "Fullstack-utvecklare",
          description:
            "Förvaltade och vidareutvecklade Studentbostäders WordPress-webbplats med fokus på användarupplevelse och prestanda.",
          skills: [
            {title: "HTML"},
            {title: "CSS"},
            {title: "JavaScript"},
            {title: "Tailwind CSS"},
            {title: "MySQL"},
            {title: "Git"},
            {title: "Bitbucket"},
            {title: "WordPress"},
          ],
        },
      ],
    },
    {
      position: "Software Engineer",
      title: "Fullstack Software Engineer at Prek",
      description:
        "Arbetade som fullstackutvecklare i ett team med mäklarsystemet Fasad. Ansvarade för både frontend och backend, från förvaltning till nyutveckling.",
      role: "Fullstack",
      company: "Prek",
      location: "Linköping",
      startDate: "Jan 2020",
      endDate: "Mar 2022",
      new_startDate: "2020-01-01",
      new_endDate: "2022-03-31",
      logotype: "/images/prek.png",
      skills: [
        {title: "HTML"},
        {title: "CSS"},
        {title: "JavaScript"},
        {title: "TypeScript"},
        {title: "jQuery"},
        {title: "Angular"},
        {title: "Vue.js"},
        {title: "PHP"},
        {title: "MySQL"},
        {title: "GitLab"},
        {title: "PhpStorm"},
        {title: "Atlassian Jira"},
        {title: "Scrum"},
        {title: "Figma"},
      ],
    },
    {
      position: "Software Engineer",
      title: "Fullstack Software Engineer at Intiro",
      role: "Fullstack",
      description:
        "Utvecklade en Xamarin-mobilapp för RTI Group som kommunicerar via Bluetooth med kalibreringsinstrument för röntgenmaskiner. Skapade användargränssnitt för datainsamling och visualisering.",
      company: "Intiro",
      location: "Linköping",
      startDate: "Aug 2019",
      endDate: "Dec 2019",
      new_startDate: "2019-08-01",
      new_endDate: "2019-12-31",
      logotype: "/images/intiro.png",
      skills: [
        {title: "HTML"},
        {title: "React.js"},
        {title: "C#"},
        {title: "Android"},
        {title: "Microsoft Xamarin"},
        {title: "Git"},
        {title: "Microsoft Azure DevOps"},
        {title: "API"},
        {title: "LAMP"},
        {title: "Atlassian Jira"},
        {title: "Figma"},
      ],
      assignments: [{title: "RTI GROUP"}],
    },
    {
      position: "Full Stack Developer",
      title: "Fullstack Developer at JobTip AB",
      description:
        "Utvecklade matchningsalgoritmer för jobbkandidater och annonser via sociala medier. Förbättrade JobTips interna publiceringsverktyg baserat på Laravel och Vue. Genomförde funktionella tester och enhetstester.",
      role: "Fullstack",
      company: "JobTip AB",
      location: "Göteborg",
      startDate: "Feb 2019",
      endDate: "Jul 2019",
      new_startDate: "2019-02-01",
      new_endDate: "2019-07-31",
      logotype: "/images/jobtip.png",
      skills: [
        {title: "HTML"},
        {title: "CSS"},
        {title: "JavaScript"},
        {title: "Vue.js"},
        {title: "PHP"},
        {title: "Laravel"},
        {title: "MySQL"},
        {title: "Amazon S3"},
        {title: "Codeception"},
        {title: "Selenium"},
        {title: "Swagger"},
      ],
    },
    {
      position: "Software Developer",
      title: "Software Developer at Stratsys AB",
      description:
        "Utvecklade och underhöll API:er med .NET Core och C#. Designade databastabeller, implementerade integreringar med externa tjänster, och utvecklade backend-lösningar för Vue.js-applikationer. Använde Jira och Scrum för projektstyrning. Hajar genomförde även LIA 1 och LIA 2 (Lärande i Arbete) på Stratsys, vardera period omfattande 3 månader.",
      role: "Fullstack",
      company: "Stratsys AB",
      location: "Göteborg",
      startDate: "Jun 2018",
      endDate: "Jan 2019",
      new_startDate: "2018-06-01",
      new_endDate: "2019-01-31",
      logotype: "/images/stratsys.png",
      skills: [
        {title: "HTML"},
        {title: "CSS"},
        {title: "JavaScript"},
        {title: "React.js"},
        {title: "Vue.js"},
        {title: ".NET"},
        {title: "C#"},
        {title: "Microsoft SQL Server"},
        {title: "Rider"},
        {title: "Atlassian Jira"},
        {title: "Scrum"},
      ],
    },
    {
      position: "Reseller",
      title: "Reseller at GameStop",
      description:
        "Arbetade som återförsäljare på GameStop Nordstan i Göteborg. Hjälpte kunder, hanterade butiken, kontrollerade konsoler samt sålde och köpte spel och hårdvara.",
      role: "Reseller",
      company: "GameStop",
      location: "Göteborg",
      startDate: "Aug 2016",
      endDate: "Jan 2017",
      new_startDate: "2016-08-01",
      new_endDate: "2017-01-31",
      logotype: "/images/gamestop.png",
      skills: [
        {title: "Sälj"},
        {title: "Kundservice"},
        {title: "Lagerhantering"},
      ],
    },
  ],
  education: [
    {
      degree: "Systemutvecklare Java",
      description:
        "Under två år studerade Hajar två examina samtidigt. Programmet bestod av 1,5 år teoretiska studier och projekt, följt av 0,5 års praktik.\n\nLäroplanen inkluderade följande ämnen:\nObjektorienterad programmering (OOP) och Java (10+ veckor av EE), samt SOLID-principer, Spring Framework, designmönster, MySQL & PostgreSQL, JDBC och Hibernate, HTML, CSS, jQuery och AJAX, JAX-RS / Jersey, SCRUM.",
      institution: "Jensen Högskola",
      location: "Göteborg, Sweden",
      startDate: "2016",
      endDate: "2018",
      new_startDate: "2016-08-01",
      new_endDate: "2018-06-30",
    },
    {
      degree: "Webbutveckling JavaScript",
      description:
        "Detta tvååriga högskoleutbildningsprogram fokuserade på Node.js-programmering.\n\nProgrammet bestod av 1,5 år teoretiska studier och projekt, följt av 0,5 års praktik.\n\nLäroplanen inkluderade följande ämnen:\nJavaScript (Node.js & NPM), MongoDB, React, Vue, HTML, CSS, jQuery och AJAX, Git, UX/UI, enhetstestning.",
      institution: "Jensen Högskola",
      location: "Göteborg, Sweden",
      startDate: "2016",
      endDate: "2018",
      new_startDate: "2016-08-01",
      new_endDate: "2018-06-30",
    },
    {
      degree: "Teknikprogrammet",
      description:
        "På Berzeliusskolan studerade Hajar Teknikprogrammet. Under sin utbildning läste han ämnen som Datateknik, Engelska, Fysik, Gränssnittsdesign, Historia, Idrott, Kemi, Matematik, Programmering, Religion, Samhällskunskap, Svenska, Webbserverprogrammering och CAD.\n\nHajar studerade webbserverprogrammering i PHP och byggde ett CMS. Han hade även programmeringskurser i Java, vilket lade grunden för hans framtida karriär inom mjukvaruutveckling.",
      institution: "Berzeliusskolan",
      location: "Linköping, Sweden",
      startDate: "2013",
      endDate: "2016",
      new_startDate: "2013-08-01",
      new_endDate: "2016-06-30",
    },
  ],
  certificates: [
    {
      name: "Foundational C# with Microsoft",
      organization: "freeCodeCamp",
      date: "Apr 2024",
      link: "https://freecodecamp.org/certification/hajarrashidi/foundational-c-sharp-with-microsoft",

    },
    {
      name: "Intermediate SQL Queries",
      organization: "DataCamp",
      date: "Nov 2023",
      link: "https://www.datacamp.com/completed/statement-of-accomplishment/course/fdc9d9190965813212b03d90ffd46274a6301448",

    },
    {
      name: "Rotarys antimobbningsprojekt",
      organization: "Rotary",
      date: "2012",
      description: "Tilldelad Rotarys stipendium för medverkan i antimobbningsarbete på skolan",
      location: "Linköping, Ånestadskolan",
    },
  ],
};
