export const cv = {
  fullName: "Hajar Rashidi",
  phone: "+46 72 448 76 18",
  email: "hajarrashidi@gmail.com",
  dob: "1996-05-24",
  website: "www.veycloud.com",
  github: "github.com/hajarrashidi",
  workExperience: [
    {
      position: "Software Engineer",
      role: "Fullstack",
      title: "Fullstack Software Engineer at Sogeti",
      description:
        "Under sin tid på Sogeti har Hajar fokuserat på webbutveckling inom flera projekt. Han har arbetat med SSAB WearIQ:s hemsida och API, byggda med Node.js och Vue.js, där han ansvarat för förvaltning och förbättring av webbplattformarna. Hos Oskarshamns kärnkraftverk var han ansvarig för underhåll av en webbapplikation utvecklad i WordPress och säkerställde att den fungerade optimalt. På Mittuniversitetet ledde Hajar integrationen av BankID i ett befintligt system med fokus på säkerhet och prestanda. Han utvecklade även ett open source-bibliotek för att underlätta BankID-integration för andra utvecklare. Hos Stångåstaden AB förvaltade och vidareutvecklade han Studentbostäders webbplats i WordPress och implementerade nya funktioner för att förbättra användarupplevelsen. Genom dessa uppdrag har Hajar visat sin förmåga att effektivt arbeta med olika webbutvecklingsteknologier och anpassa sig till olika projektbehov.",
      company: "Sogeti",
      location: "Linköping",
      startDate: "March 2022",
      endDate: "Nuvarande",
      logotype: "/images/sogeti.png",
      skills: [
        // Frontend
        {title: "HTML"},
        {title: "CSS"},
        {title: "JavaScript"},
        {title: "TypeScript"},
        {title: "React.js"},
        {title: "Vue.js"},
        {title: "Tailwind CSS"},
        // Backend
        {title: "Node.js"},
        {title: "PHP"},
        {title: "Laravel"},
        // Mobile
        {title: "Android Studio"},
        {title: "Flutter"},
        {title: "Dart"},
        // Database
        {title: "SQL Server"},
        {title: "MySQL"},
        // Version Control
        {title: "Git"},
        {title: "Bitbucket"},
        // Cloud & DevOps
        {title: "Azure"},
        {title: "Azure DevOps"},
        // CMS
        {title: "WordPress"},
        // API
        {title: "REST API"},
        // Package Management
        {title: "Composer"},
        // Project Management
        {title: "Jira"},
        // Design
        {title: "Figma"},
      ],
      assignments: [
        {
          title: "LFV",
          period: "November 2023 – Nuvarande",
          role: "Fullstack-utvecklare",
          description:
            "Hajar arbetar med att utveckla och underhålla LFV:s interna system för flygtrafikledning. Han använder sin expertis inom fullstack-utveckling för att förbättra systemets funktionalitet och användarupplevelse.",
          skills: [
            {title: "React.js"},
            {title: "Node.js"},
            {title: "TypeScript"},
            {title: "Azure DevOps"},
          ],
        },
        {
          title: "SSAB",
          period: "October 2023",
          role: "Systemutvecklare",
          description:
            "Hajar förvaltade SSAB WearIQ:s mobilapp, hemsida och API. Appen är utvecklad i Flutter, medan hemsidan och API:et är utvecklade i Node.js, med Vue.js för frontend. Hans arbete säkerställde en sömlös drift och förbättring av dessa plattformar, med fokus på användarupplevelse och systemintegration.",
          skills: [
            {title: "HTML"},
            {title: "CSS"},
            {title: "JavaScript"},
            {title: "TypeScript"},
            {title: "React.js"},
            {title: "Vue.js"},
            {title: "Node.js"},
            {title: "Android Studio"},
            {title: "Flutter"},
            {title: "Dart"},
            {title: "Git"},
            {title: "Microsoft Azure"},
            {title: "Microsoft Azure DevOps"},
            {title: "Figma"},
          ],
        },
        {
          title: "Oskarshamns kärnkraftverk",
          period: "October 2023",
          role: "Systemutvecklare",
          description:
            "Hajar förvaltade OKG:s mobilapp och webbapp. Hemsidan var utvecklad i WordPress och mobilappen i Flutter. Han såg till att båda plattformarna var uppdaterade och fungerade optimalt, med särskilt fokus på säkerhet och prestanda i den känsliga miljön.",
          skills: [
            {title: "HTML"},
            {title: "CSS"},
            {title: "JavaScript"},
            {title: "PHP"},
            {title: "Flutter"},
            {title: "Dart"},
            {title: "Git"},
            {title: "Microsoft Azure DevOps"},
            {title: "WordPress"},
            {title: "REST API"},
            {title: "Figma"},
          ],
        },
        {
          title: "Mittuniversitetet",
          period: "January 2023 – September 2023",
          role: "Fullstack-utvecklare",
          description:
            "Hajar hade en ledande roll i att integrera BankID i ett befintligt system hos Mittuniversitetet. Han designade och implementerade integrationen med starkt fokus på säkerhet och prestanda. Genom att identifiera ett bredare behov utvecklade han även ett open source-bibliotek för att hjälpa andra utvecklare att mer effektivt integrera BankID version 6, vilket demonstrerade hans förmåga att tänka innovativt och bidra till utvecklargemenskapen.",
          skills: [
            {title: "HTML"},
            {title: "CSS"},
            {title: "JavaScript"},
            {title: "PHP"},
            {title: "Laravel"},
            {title: "Microsoft SQL Server"},
            {title: "Composer"},
            {title: "Atlassian Jira"},
            {title: "Figma"},
          ],
        },
        {
          title: "Stångåstaden AB",
          period: "August 2022 – January 2023",
          role: "Fullstack-utvecklare",
          description:
            "Som fullstack-utvecklare var Hajar ansvarig för förvaltning och fortsatt utveckling av webbsidan för Studentbostäder, byggd i WordPress. Han säkerställde att webbplatsen mötte behoven hos studenter som söker boende och implementerade nya funktioner vid behov. Hans arbete fokuserade på att förbättra användarupplevelsen och optimera webbplatsens prestanda.",
          skills: [
            {title: "HTML"},
            {title: "CSS"},
            {title: "JavaScript"},
            {title: "Tailwind CSS"},
            {title: "MySQL"},
            {title: "Git"},
            {title: "Bitbucket"},
            {title: "WordPress"},
          ],
        },
      ],
    },
    {
      position: "Software Engineer",
      title: "Fullstack Software Engineer at Prek",
      description:
        "På Prek arbetade Hajar som fullstackutvecklare i ett team med ett mäklarsystem kallat Fasad. Han hade ansvar för både frontend och backend. Under sina två år på Prek arbetade han med allt från förvaltning till nyutveckling, vilket gav honom bred erfarenhet inom systemutveckling och projekthantering.",
      role: "Fullstack",
      company: "Prek",
      location: "Linköping",
      startDate: "January 2020",
      endDate: "March 2022",
      logotype: "/images/prek.png",
      skills: [
        {title: "HTML"},
        {title: "CSS"},
        {title: "JavaScript"},
        {title: "TypeScript"},
        {title: "jQuery"},
        {title: "Angular"},
        {title: "Vue.js"},
        {title: "PHP"},
        {title: "MySQL"},
        {title: "GitLab"},
        {title: "PhpStorm"},
        {title: "Atlassian Jira"},
        {title: "Scrum"},
        {title: "Figma"},
      ],
    },
    {
      position: "Software Engineer",
      title: "Fullstack Software Engineer at Intiro",
      role: "Fullstack",
      description:
        "RTI Group tillverkar kalibreringsinstrument för röntgenmaskiner. Som konsult på Intiro utvecklade Hajar en mobilapp i Xamarin som kommunicerar via Bluetooth med kalibreringsinstrumentet. Instrumentet används inom vården för att säkerställa att patienter inte utsätts för överdriven strålning. Hajar skapade ett användarvänligt gränssnitt för datainsamling och visualisering, använde Figma för prototypdesign och säkerställde smidig kommunikation mellan appen och instrumentet. Detta projekt demonstrerade hans förmåga att arbeta med specialiserad teknik och skapa lösningar för kritiska användningsområden.",
      company: "Intiro",
      location: "Linköping",
      startDate: "August 2019",
      endDate: "December 2019",
      logotype: "/images/intiro.png",
      skills: [
        {title: "HTML"},
        {title: "React.js"},
        {title: "C#"},
        {title: "Android"},
        {title: "Microsoft Xamarin"},
        {title: "Git"},
        {title: "Microsoft Azure DevOps"},
        {title: "API"},
        {title: "LAMP"},
        {title: "Atlassian Jira"},
        {title: "Figma"},
      ],
      assignments: [{title: "RTI GROUP"}],
    },
    {
      position: "Full Stack Developer",
      title: "Fullstack Developer at JobTip AB",
      description:
        "Inom JobTip var Hajar ansvarig för utvecklingen av algoritmer för att effektivt matcha potentiella kandidater med lämpliga annonser via sociala medieplattformar. Hans arbetsansvar inkluderade också förbättring och vidareutveckling av JobTips interna publiceringsverktyg, baserat på Laravel-ramverket och Vue. Han genomförde även funktionella tester samt enhetstester, vilket bidrog till att säkerställa hög kvalitet och pålitlighet i systemet.",
      role: "Fullstack",
      company: "JobTip AB",
      location: "Göteborg",
      startDate: "February 2019",
      endDate: "July 2019",
      logotype: "/images/jobtip.png",
      skills: [
        {title: "HTML"},
        {title: "CSS"},
        {title: "JavaScript"},
        {title: "Vue.js"},
        {title: "PHP"},
        {title: "Laravel"},
        {title: "MySQL"},
        {title: "Amazon S3"},
        {title: "Codeception"},
        {title: "Selenium"},
        {title: "Swagger"},
      ],
    },
    {
      position: "Software Developer",
      title: "Software Developer at Stratsys AB",
      description:
        "På Stratsys, ett företag som utvecklar molnbaserad mjukvara för strategisk planering, arbetade Hajar i ett team om fem personer. Han ansvarade för utveckling och underhåll av API:er med hjälp av .NET Core och C#. Han designade databastabeller för optimerad datalagring och -hämtning samt implementerade integreringar med externa tjänster och system. I samarbete med frontend-teamet utvecklade han backend-lösningar till Vue.js-applikationer. Hajar använde Jira för effektiv projektstyrning och deltog aktivt i Scrum-processen för agil utveckling, vilket förbättrade teamets produktivitet och samarbete.",
      role: "Fullstack",
      company: "Stratsys AB",
      location: "Göteborg",
      startDate: "June 2018",
      endDate: "January 2019",
      logotype: "/images/stratsys.png",
      skills: [
        {title: "HTML"},
        {title: "CSS"},
        {title: "JavaScript"},
        {title: "React.js"},
        {title: "Vue.js"},
        {title: ".NET"},
        {title: "C#"},
        {title: "Microsoft SQL Server"},
        {title: "Rider"},
        {title: "Atlassian Jira"},
        {title: "Scrum"},
      ],
    },
    {
      position: "Reseller",
      title: "Reseller at GameStop",
      description:
        "Under studietiden arbetade Hajar som återförsäljare på GameStop Nordstan i Göteborg. Hans arbetsuppgifter inkluderade att hjälpa kunder att hitta spel, sortera och städa butiken, kontrollera trasiga konsoler samt att sälja och köpa konsolspel och hårdvara. Denna erfarenhet gav honom värdefull kunskap inom kundservice, försäljning och lagerhantering, vilket har varit användbart i hans senare karriär som utvecklare när det gäller att förstå kundbehov och affärsprocesser.",
      role: "Reseller",
      company: "GameStop",
      location: "Göteborg",
      startDate: "August 2016",
      endDate: "January 2017",
      logotype: "/images/gamestop.png",
      skills: [
        {title: "Sälj"},
        {title: "Kundservice"},
        {title: "Lagerhantering"},
      ],
    },
  ],
  education: [
    {
      degree: "Systemutvecklare Java",
      description:
        "Under två år studerade Hajar två examina samtidigt. Programmet bestod av 1,5 år teoretiska studier och projekt, följt av 0,5 års praktik.\n\nLäroplanen inkluderade följande ämnen:\nObjektorienterad programmering (OOP) och Java (10+ veckor av EE), samt SOLID-principer, Spring Framework, designmönster, MySQL & PostgreSQL, JDBC och Hibernate, HTML, CSS, jQuery och AJAX, JAX-RS / Jersey, SCRUM.",
      institution: "Jensen Högskola",
      location: "Göteborg, Sweden",
      startDate: "2016",
      endDate: "2018",
    },
    {
      degree: "Webbutveckling JavaScript",
      description:
        "Detta tvååriga högskoleutbildningsprogram fokuserade på Node.js-programmering.\n\nProgrammet bestod av 1,5 år teoretiska studier och projekt, följt av 0,5 års praktik.\n\nLäroplanen inkluderade följande ämnen:\nJavaScript (Node.js & NPM), MongoDB, React, Vue, HTML, CSS, jQuery och AJAX, Git, UX/UI, enhetstestning.",
      institution: "Jensen Högskola",
      location: "Göteborg, Sweden",
      startDate: "2016",
      endDate: "2018",
    },
    {
      degree: "Teknikprogrammet",
      description:
        "På Berzeliusskolan studerade Hajar Teknikprogrammet. Under sin utbildning läste han ämnen som Datateknik, Engelska, Fysik, Gränssnittsdesign, Historia, Idrott, Kemi, Matematik, Programmering, Religion, Samhällskunskap, Svenska, Webbserverprogrammering och CAD.\n\nHajar studerade webbserverprogrammering i PHP och byggde ett CMS. Han hade även programmeringskurser i Java, vilket lade grunden för hans framtida karriär inom mjukvaruutveckling.",
      institution: "Berzeliusskolan",
      location: "Linköping, Sweden",
      startDate: "2013",
      endDate: "2016",
    },
  ],
  certificates: [
    {
      name: "Foundational C# with Microsoft",
      organization: "freeCodeCamp",
      date: "April 2024",
      link: "https://freecodecamp.org/certification/hajarrashidi/foundational-c-sharp-with-microsoft",
      
    },
    {
      name: "Intermediate SQL Queries",
      organization: "DataCamp",
      date: "November 2023",
      link: "https://www.datacamp.com/completed/statement-of-accomplishment/course/fdc9d9190965813212b03d90ffd46274a6301448",
      
    },
    {
      name: "Rotarys antimobbningsprojekt",
      organization: "Rotary",
      date: "2012",
      description: "Hajar Rashidi har tilldelats Rotarys stipendium för att ha medverkat till antimobbning på skolan",
      location: "Linköping, Ånestadskolan",
    },
  ],
};
