export const cv = {
  fullName: "Hajar Rashidi",
  phone: "+46 72 448 76 18",
  email: "hajarrashidi@gmail.com",
  dob: "1996-05-24",
  github: "github.com/hajarrashidi",
  workExperience: [
    {
      position: "Software Engineer",
      role: "Fullstack",
      title: "Fullstack Software Engineer at Sogeti",
      description:
      "" +
        "" +
        "Under sin tid på Sogeti har Hajar fokuserat på webbutveckling inom flera projekt. Han arbetade med SSAB WearIQ:s hemsida och API, byggda med Node.js och Vue.js, där han ansvarade för förvaltning och förbättring av webbplattformarna. Hos Oskarshamns kärnkraftverk var han ansvarig för underhåll av webbapplikationen utvecklad i WordPress och säkerställde att den fungerade optimalt. På Mittuniversitetet ledde Hajar integrationen av BankID i ett befintligt system med fokus på säkerhet och prestanda. Han utvecklade även ett open source-bibliotek för att underlätta BankID-integration för andra utvecklare. Hos Stångåstaden AB förvaltade och vidareutvecklade han Studentbostäders webbplats i WordPress, implementerade nya funktioner för att förbättra användarupplevelsen. Genom dessa uppdrag har Hajar visat sin förmåga att effektivt arbeta med olika webbutvecklingsteknologier" +
        "" +
        "",
      company: "Sogeti",
      location: "Linköping",
      startDate: "March 2022",
      endDate: "Fortfarande anställd",
      logotype: "/images/sogeti.png",
      skills: [
        { title: "Android Studio" },
        { title: "Bitbucket" },
        { title: "Composer" },
        { title: "CSS" },
        { title: "Dart" },
        { title: "Figma" },
        { title: "Flutter" },
        { title: "Git" },
        { title: "HTML" },
        { title: "JavaScript" },
        { title: "Laravel" },
        { title: "Azure" },
        { title: "Azure DevOps" },
        { title: "SQL Server, MySQL" },
        { title: "Node.js" },
        { title: "PHP" },
        { title: "React.js" },
        { title: "REST API's" },
        { title: "Tailwind CSS" },
        { title: "TypeScript" },
        { title: "Vue.js" },
        { title: "WordPress" },
        { title: "Jira" },
      ],
      assignments: [
        {
          title: "LFV"
        },
        {
          title: "SSAB",
          period: "October 2023",
          role: "Systemutvecklare",
          description:
            "Förvaltade SSAB WearIQ mobilapp, hemsida och API. Appen är utvecklad i Flutter medan hemsidan och API:et är utvecklat i Node.js, med Vue.js för frontend. Hans arbete säkerställde en sömlös drift och förbättring av dessa plattformar.",
          skills: [
            { title: "Android Studio" },
            { title: "CSS" },
            { title: "Dart" },
            { title: "Flutter" },
            { title: "Git" },
            { title: "HTML" },
            { title: "JavaScript" },
            { title: "TypeScript" },
            { title: "Microsoft Azure" },
            { title: "Microsoft Azure DevOps" },
            { title: "Node.js" },
            { title: "React.js" },
            { title: "Vue.js" },
            { title: "Figma" },
          ],
        },
        {
          title: "Oskarshamns kärnkraftverk",
          period: "October 2023",
          role: "Systemutvecklare",
          description:
            "Förvaltade OKG mobilapp och webapp. Hemsidan var utvecklad i WordPress och mobilappen i Flutter. Hajar såg till att båda plattformarna var uppdaterade och fungerade optimalt.",
          skills: [
            { title: "CSS" },
            { title: "Dart" },
            { title: "Flutter" },
            { title: "Git" },
            { title: "HTML" },
            { title: "JavaScript" },
            { title: "Microsoft Azure DevOps" },
            { title: "PHP" },
            { title: "REST API's" },
            { title: "WordPress" },
            { title: "Figma" },
          ],
        },
        {
          title: "Mittuniversitetet",
          period: "January 2023 – September 2023",
          role: "Fullstack-utvecklare",
          description:
            "Hade en ledande roll i att integrera BankID i ett befintligt system hos Mittuniversitetet. Han designade och implementerade integrationen med starkt fokus på säkerhet och prestanda. Genom att identifiera ett bredare behov utvecklade han även ett open source-bibliotek för att hjälpa andra utvecklare att mer effektivt integrera BankID version 6.",
          skills: [
            { title: "Atlassian Jira" },
            { title: "Composer" },
            { title: "CSS" },
            { title: "HTML" },
            { title: "JavaScript" },
            { title: "Laravel" },
            { title: "Microsoft SQL Server" },
            { title: "PHP" },
            { title: "Figma" },
          ],
        },
        {
          title: "Stångåstaden AB",
          period: "August 2022 – January 2023",
          role: "Fullstack-utvecklare",
          description:
            "Fullstack-utvecklare ansvarig för förvaltning och fortsatt utveckling av webbsidan för Studentbostäder, byggd i WordPress. Han säkerställde att webbplatsen mötte behoven hos studenter som söker boende och implementerade nya funktioner vid behov.",
          skills: [
            { title: "Bitbucket" },
            { title: "CSS" },
            { title: "Git" },
            { title: "HTML" },
            { title: "JavaScript" },
            { title: "MySQL" },
            { title: "Tailwind CSS" },
            { title: "WordPress" },
          ],
        },
      ],
    },
    {
      position: "Software Engineer",
      title: "Fullstack Software Engineer at Prek",
      description:
        "Hajar arbetade som fullstackutvecklare i ett team på Prek med ett mäklarsystem som heter Fasad. Där hade han hand om både frontend och backend. Under Hajars två år på Prek arbetade han med allt från förvaltning till nyutveckling.",
      role: "Fullstack",
      company: "Prek",
      location: "Linköping",
      startDate: "January 2020",
      endDate: "March 2022",
      logotype: "/images/prek.png",
      skills: [
        { title: "Atlassian Jira" },
        { title: "CSS" },
        { title: "GitLab" },
        { title: "HTML" },
        { title: "JavaScript" },
        { title: "TypeScript" },
        { title: "jQuery" },
        { title: "MySQL" },
        { title: "PHP" },
        { title: "PhpStorm" },
        { title: "Angular" },
        { title: "Scrum" },
        { title: "Vue.js" },
        { title: "Figma" },
      ],
    },
    {
      position: "Software Engineer",
      title: "Fullstack Software Engineer at Intiro",
      role: "Fullstack",
      description:
        "RTI Group tillverkar kalibreringsinstrument för röntgenmaskiner. Som konsult på Intiro utvecklade Hajar en mobilapp i Xamarin som kommunicerar via Bluetooth med kalibreringsinstrumentet. Instrumentet används inom vården för att säkerställa att patienter inte utsätts för överdriven strålning. Hajar skapade ett användarvänligt gränssnitt för datainsamling och visualisering, använde Figma för prototypdesign och säkerställde smidig kommunikation mellan appen och instrumentet.",
      company: "Intiro",
      location: "Linköping",
      startDate: "August 2019",
      endDate: "December 2019",
      logotype: "/images/intiro.png",
      skills: [
        { title: "Android" },
        { title: "Atlassian Jira" },
        { title: "C#" },
        { title: "Figma" },
        { title: "Git" },
        { title: "Microsoft Azure DevOps" },
        { title: "Microsoft Xamarin" },
        { title: "API" },
        { title: "HTML" },
        { title: "LAMP" },
        { title: "React.js" },
      ],
      assignments: [{ title: "RTI GROUP" }],
    },
    {
      position: "Full Stack Developer",
      title: "Fullstack Developer at JobTip AB",
      description:
        "Inom Jobtip var Hajar ansvarig för utvecklingen av algoritmer för att effektivt matcha potentiella kandidater med lämpliga annonser via sociala medieplattformar. Hans arbetsansvar inkluderade också förbättring och vidareutveckling av Jobtips interna publiceringsverktyg, baserat på Laravel-ramverket och Vue. Han genomförde även funktionella tester samt enhetstester.",
      role: "Fullstack",
      company: "JobTip AB",
      location: "Göteborg",
      startDate: "February 2019",
      endDate: "July 2019",
      logotype: "/images/jobtip.png",
      skills: [
        { title: "Amazon S3" },
        { title: "Codeception" },
        { title: "CSS" },
        { title: "HTML" },
        { title: "Laravel" },
        { title: "MySQL" },
        { title: "PHP" },
        { title: "Selenium" },
        { title: "Swagger" },
        { title: "Vue.js" },
        { title: "JavaScript" },
      ],
    },
    {
      position: "Software Developer",
      title: "Software Developer at Stratsys AB",
      description:
        "Hajar arbetade i ett team av fem personer på Stratsys, molnbaserad mjukvara för strategisk planering. Han ansvarade för utveckling och underhåll av API:er med hjälp av .NET Core och C#. Han designade databastabeller för optimerad dataförvaring och hämtning samt implementerade integreringar med externa tjänster och system. I samarbete med frontend-teamet utvecklade han backend-lösningar till Vue.js-applikationer. Hajar använde Jira för effektiv projektstyrning och deltog aktivt i Scrum-processen för agil utveckling.",
      role: "Fullstack",
      company: "Stratsys AB",
      location: "Göteborg",
      startDate: "June 2018",
      endDate: "January 2019",
      logotype: "/images/stratsys.png",
      skills: [
        { title: ".NET" },
        { title: "Atlassian Jira" },
        { title: "C#" },
        { title: "CSS" },
        { title: "HTML" },
        { title: "JavaScript" },
        { title: "Microsoft SQL Server" },
        { title: "React.js" },
        { title: "Rider" },
        { title: "Scrum" },
        { title: "Vue.js" },
      ],
    },
    {
      position: "Reseller",
      title: "Reseller at GameStop",
      description:
        "Hajar arbetade som återförsäljare på GameStop Nordstan i Göteborg under studietiden. Hans arbetsuppgifter inkluderade att hjälpa kunder att hitta spel, sortera och städa butiken, kontrollera trasiga konsoler samt att sälja och köpa konsolspel och hårdvara.",
      role: "Reseller",
      company: "GameStop",
      location: "Göteborg",
      startDate: "August 2016",
      endDate: "January 2017",
      logotype: "/images/gamestop.png",
      skills: [],
    },
  ],
  education: [
    {
      degree: "Systemutvecklare Java",
      description:
        "Hajar studerade två examina samtidigt under de två åren av sina studier. Programmet bestod av 1,5 år av teoretiska studier och projekt, följt av 0,5 års praktik.\n\nLäroplanen inkluderade följande ämnen:\nObjektorienterad programmering (OOP) och Java (10+ veckor av EE), samt SOLID-principer, Spring Framework, designmönster, MySQL & PostgreSQL, JDBC och Hibernate, HTML, CSS, jQuery och AJAX\nJAX-RS / Jersey, SCRUM.",
      institution: "Jensen Högskola",
      location: "Göteborg, Sweden",
      startDate: "2016",
      endDate: "2018",
    },
    {
      degree: "Webbutveckling JavaScript",
      description:
        "Tvåårigt högskoleutbildningsprogram inom Node.js-programmering.\n\nProgrammet består av 1,5 år av teoretiska studier och projekt, följt av 0,5 års praktik.\n\nLäroplanen inkluderar följande ämnen:\nJavaScript (Node.js & NPM), MongoDB, React, Vue, HTML, CSS, jQuery och AJAX, Git, UX/UI, enhetstestning.",
      institution: "Jensen Högskola",
      location: "Göteborg, Sweden",
      startDate: "2016",
      endDate: "2018",
    },
    {
      degree: "Teknikprogrammet",
      description: "",
      institution: "Berzeliusskolan",
      location: "Linköping, Sweden",
      startDate: "2016",
      endDate: "2016",
    },
  ],
  certificates: [
    {
      name: "Foundational C# with Microsoft",
      organization: "freeCodeCamp",
      date: "April 2024",
      link: "https://freecodecamp.org/certification/hajarrashidi/foundational-c-sharp-with-microsoft",
    },
    {
      name: "Intermediate SQL Queries",
      organization: "DataCamp",
      date: "November 2023",
      link: "https://www.datacamp.com/completed/statement-of-accomplishment/course/fdc9d9190965813212b03d90ffd46274a6301448",
    },
  ],
};