export const cv = {
  fullName: "Hajar Rashidi",
  workExperience: [
    {
      position: "Software Engineer",
      company: "Sogeti",
      location: "Linköping",
      startDate: "March 2022",
      endDate: "Present",
      logotype: "/images/sogeti.png",
      assignments: [
        { title: "Mittuniversitetet" },
        { title: "SSAB" },
        { title: "Stångåstaden Studentbostäder" },
        { title: "Oskarshamns kärnkraftverk" },
        { title: "Samhall" },
        { title: "Luftfartsverket" },
      ],
    },
    {
      position: "Software Engineer",
      company: "Prek",
      location: "Linköping",
      startDate: "January 2020",
      endDate: "March 2022",
      logotype: "/images/prek.png",
    },
    {
      position: "Software Engineer",
      company: "Intiro",
      location: "Linköping",
      startDate: "August 2019",
      endDate: "December 2019",
      logotype: "/images/intiro.png",
      assignments: [
        { title: "RTI GROUP" },
      ],
    },
    {
      position: "Full Stack Developer",
      company: "JobTip AB",
      location: "Göteborg",
      startDate: "February 2019",
      endDate: "July 2019",
      logotype: "/images/jobtip.png",
    },
    {
      position: "Software Developer",
      company: "Stratsys AB",
      location: "Göteborg",
      startDate: "June 2018",
      endDate: "January 2019",
      logotype: "/images/stratsys.png",
    },
    {
      position: "Reseller",
      company: "GameStop",
      location: "Göteborg",
      startDate: "August 2016",
      endDate: "January 2017",
      logotype: "/images/gamestop.png",
    },
  ],
  education: [
    {
      degree: "Software Developer Java",
      institution: "Jensen YH",
      location: "Göteborg, Sweden",
      startDate: "2016",
      endDate: "2018",
    },
    {
      degree: "Web Developer JavaScript",
      institution: "Jensen YH",
      location: "Göteborg, Sweden",
      startDate: "2016",
      endDate: "2018",
    },
  ],
};
